### PR TITLE
Revert "Update README.md"

### PR DESCRIPTION
**Pull request by philb38**
Reverts philb38/pet-clinic#10

### CODE REVIEW

**Comment by philb38** [comment]
@tina done

**Comment by philb38** [comment]
@tina done

**Comment by philb38** [comment]
@tina done

**Comment by philb38** [comment]
@tine done

**Comment by philb38** [comment]
@tina done

**Comment by philb38** [comment]
@tina done

**Comment by philb38** [comment]
@tina done

**Comment by philb38** [comment]
@tina done

**Comment by philb38** [comment]
@tina look

**Comment by philb38** [comment]
@tina look

**Comment by philb38** [comment]
@tina look

**Comment by philb38** [comment]
/ tina look

**Comment by philb38** [comment]
mmm / tina, look!

**Comment by philb38** [comment]
mmm / tina, look!

**Comment by philb38** [comment]
/ tina, look!

**Comment by philb38** [comment]
mmm / tina, look!

**Comment by pberthonneau** [comment]
/ tina look

**Comment by pberthonneau** [comment]
/ tina look

**Comment by pberthonneau** [comment]
/ tina look

**Comment by philb38** [comment]
/ hal

**Comment by pberthonneau** [comment]
/ hal

**Comment by pberthonneau** [comment]
/ hal

**Comment by philb38** [comment]
/paulo - can you please review this pull request?

**Pull request merged**
